name: geoflood
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - scikit-image
  - numba
  - matplotlib
  - pandas
  - psutil
  - rasterio
  - scipy
  - statsmodels
  - gdal
  - dask
  - numpy
  - scikit-fmm
  - affine
  - netcdf4
  - geopandas
