export LOCATION_NAME="${PROJECT}"
export WORKING_DIRECTORY='/scratch/04950/dhl/GeoFlood/GeoFlood-NOAA'
export PROJECT_CFG="${WORKING_DIRECTORY}/GeoFlood_${PROJECT}.cfg"
export PATH_TASK_PROC='/scratch/04950/dhl/GeoFlood/GeoFlood-NOAA/GeoFlood-Task_processor/geoflood-task_processor'
export PATH_GEOFLOOD='/scratch/04950/dhl/GeoFlood/GeoFlood-NOAA/GeoFlood'
export PATH_GEOINPUTS='/scratch/04950/dhl/GeoFlood/GeoFlood-NOAA/GeoInputs'
export PATH_GEOOUTPUTS='/scratch/04950/dhl/GeoFlood/GeoFlood-NOAA/GeoOutputs'
export PATH_CONDA_FUNCS='/scratch/04950/dhl/GeoFlood/GeoFlood-NOAA/GeoFlood-Task_processor/geoflood-task_processor/conda_wrappers.sh'
source $PATH_CONDA_FUNCS
